name: golangci-lint

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.18.x"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.50.1
          args: --timeout=10m
